config/routes.rb
Threepo::Application.routes.draw do
  devise_for :users

  root 'designs#index'

  resources :designs do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :design, inverse_of: :comments
  belongs_to :user, inverse_of: :comments

  validates_presence_of :body

end

app/models/design.rb
class Design < ActiveRecord::Base
  validates_presence_of :description
  validates_presence_of :title

  belongs_to :user, inverse_of: :designs, dependent: :destroy

  has_many :comments, inverse_of: :design

  mount_uploader :image, ImageUploader
  mount_uploader :file, FileUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments, inverse_of: :user
  has_many :designs, inverse_of: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @design = Design.find(params[:design_id])
    @design.user = current_user
    @comment = @design.comments.new(comment_params)
    save_comment
  end

  def destroy
    design = Design.find(params[:design_id])
    comment = design.comments.find(params[:id])
    comment.destroy
    redirect_to design_path(design)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def save_comment
    if @comment.save
      redirect_to design_path(@design), notice: "Comment successfully added."
    else
      redirect_to design_path(@design), notice: "There was an error. Your comment did not save."
    end
  end

end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]

  def index
    @query = Design.search(params[:q])
    @designs = @query.result(distinct: true)
  end

  def new
    @design = Design.new
  end

  def create
    @design = Design.new(design_params)
    @design.user = current_user
    save_design
  end

  def show
    @design = Design.find(params[:id])
  end

  def destroy
    design = Design.find(params[:id])
    design.destroy
    redirect_to designs_path
  end

  private

  def design_params
    params.require(:design).permit(:title, :description, :image, :file)
  end

  def save_design
    if @design.save
      redirect_to @design, notice: "Successfully uploaded design"
    else
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<%- if comment.persisted? %>
<br>
<div class="panel panel-default panel-body">
  <%= comment.body %><br>
  <small>on <%= comment.created_at %></small><br>
</div>

<p>
  <%= link_to 'Delete Comment', [comment.design, comment],
  method: :delete,
  data: { confirm: 'Are you sure?' } %>
</p>
<%- end -%>

app/views/comments/_form.html.erb
<%= simple_form_for([@design, @design.comments.build]) do |f| %>
  <%= f.input :body, :label => false %><br>
  <%= f.submit class: "btn-info btn-default" %>
<% end %>

app/views/designs/_design.html.erb
<div class="design">
  <br><%= link_to image_tag(design.image_url(:index_thumb)),
  design_path(design), class: "designs-frontpage", input_html:
  { rel: "shadowbox" } %>
  <br><h3><%= design.title %></h3>
  <%= link_to 'Delete Design', design_path(design), method: :delete,
  data: { confirm: 'Are you sure?' } %>
</div>

app/views/designs/index.html.erb
<div class="container">
  <div class="row top-row">
    <h1>Welcome to threepo, the world's greatest 3d-print design repo</h1>
  </div>

  <div class="col-md-3 pull-right">
    <% if user_signed_in? %>
      <div class="alert alert-dismissable alert-info">
      <p>Have a design you'd like to share?</p><br>
      <%= link_to 'Upload your design', new_design_path, class:
      "btn btn-primary btn-lg btn-block" %>
      </div>
    <% end %>
  </div>
</div>

<div class="well">
  <div class="text-center">
  <%= search_form_for @query do |f| %>
    <%= f.label "Find your design " %>
    <%= f.text_field :title_cont %>
    <%= f.submit class: 'btn-info btn-default'%>
  <% end %><br>
  </div>

  <div class="row design-rows">
    <div class="col-md-10 col-md-offset-1">
      <%= render @designs %>
    </div>
  </div>
</div>

app/views/designs/new.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="well">
      <div class="row">
        <div class="form-horizontal">
          <div class="text-center">
            <h1> Upload Design </h1>
          </div>
          <%= simple_form_for Design.new, html: {multipart: true} do |f| %>
          <%= f.input :title, label: "Name your design!" %><br><br>
          <%= f.input :description, label:
          "Describe your design!" %><br>
          <%= f.input :image, input_html: {id: 'image'}, label: "Upload a picture
          of your design (jpg/png)" %><br><br>
          <%= f.input :file, input_html: {id: 'file'}, label: "Upload your design
          (CAD)" %><br><br>
          <div id="image_preview"></div>
          <%= f.button :submit, "Upload Your Design", class: 'btn-primary btn-lg sign-up-btn' %><br><br>
          <%- end -%>

          <%= javascript_include_tag "preview" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/designs/show.html.erb
<div class="well">
  <div class="row">
    <div class="col-md-5 col-md-offset-3">
      <div>
      <%= image_tag @design.image_url(:thumb) %>
      </div>
    </div>
  </div><br><br>

<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-primary">
      <div class="panel-heading text-center">
        <div class="panel-title"><h2><%= @design.title %></h2></div>
      </div>

      <div class="panel-body">
        <h4>"<%= @design.description %>"<br><br>
        - <%= @design.user.email %></h4>
      </div>
    </div>
  </div>
</div>

<div class="container">
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <% if user_signed_in? %>
      <h2>Add a comment:</h2>
      <%= render "comments/form" %>
    <% end %>

    <%= render @design.comments %>
    <div class="text-center">
      <%= link_to 'Back to Home', designs_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>threepo</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">threepo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><a href="#">New Designs</a></li>
        <li><a href="#">Popular Designs</a></li>
        <li><a href="#">About</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit account", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          </ul>
          <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <%= notice %>
    <%= alert %>
    <%= yield %>
  </div>
</body>
</html>